import type React from "react";
import type { Metadata } from "next";
import "./globals.css";
import { WalletProvider } from "@/providers/web3provider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { MeshProvider, useWallet as useMeshWallet } from "@meshsdk/react";
import { LaceWalletProvider } from "@/providers/lace-wallet-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <WalletProvider>
          {/* <MeshProvider> */}
          <LaceWalletProvider>
            <Navbar />
            {children}
            <Footer />
            {/* </MeshProvider> */}/
          </LaceWalletProvider>
        </WalletProvider>
      </body>
    </html>
  );
}
